# Generated by Django 5.2.4 on 2025-10-27 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                ("amt", models.DecimalField(decimal_places=2, max_digits=12)),
                ("city", models.CharField(max_length=100)),
                ("card_number", models.CharField(blank=True, max_length=16, null=True)),
                ("cvv", models.CharField(blank=True, max_length=4, null=True)),
                ("expiry_date", models.CharField(blank=True, max_length=7, null=True)),
                ("hour", models.PositiveSmallIntegerField()),
                ("dow", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ml_prob", models.FloatField(blank=True, null=True)),
                ("rule_avg_last_n", models.FloatField(blank=True, null=True)),
                ("rule_multiplier_used", models.FloatField(blank=True, null=True)),
                ("rule_delta_used", models.FloatField(blank=True, null=True)),
                ("rule_flag", models.BooleanField(default=False)),
                ("otp_required", models.BooleanField(default=False)),
                ("otp_id", models.CharField(blank=True, max_length=64, null=True)),
                ("otp_verified", models.BooleanField(default=False)),
                (
                    "final_decision",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("challenge", "Challenged (OTP sent)"),
                            ("approved", "Approved after OTP"),
                            ("blocked", "Blocked / OTP failed"),
                        ],
                        default="allowed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="txns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
